services:
  java_training_db:
    image: postgres:16
    container_name: java_training_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    ports:
      - "5436:5432"

  java_training_pgadmin:
    image: dpage/pgadmin4
    container_name: java_training_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8086:80"
    depends_on:
      - java_training_db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgadmin_data: